import { cookies } from 'next/headers';
import { getCookie } from "cookies-next";
import "../../../components/styles/form-root.css"
import Header from "../../../components/layout/header";
import Navigation from "../../../components/layout/navigation";
import Footer from "../../../components/layout/footer";
import Aside from '../../../components/layout/aside';

export const metadata = {
  title: '회원 수정',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  var state = getCookie("state", {cookies});

  if(state == null){
    state = '2';
  }
  
  if(state != '1'){
    return (
      <html lang="en">
         <head>
          <link rel="stylesheet" href="/css/form-noaside.css" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossOrigin="anonymous" />
        </head>
        <body>
          <Header/>
          <Navigation/>
          <main>
            {children}
          </main>
          <Footer/>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossOrigin="anonymous"></script>
        </body>
      </html>
    );
  }else{
    return (
      <html lang="en">
         <head>
          <link rel="stylesheet" href="/css/form-base.css" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossOrigin="anonymous" />
        </head>
        <body>
          <Header/>
          <Navigation/>
          <Aside id={"기타"}/>
          <main>
            {children}
          </main>
          <Footer/>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossOrigin="anonymous"></script>
        </body>
      </html>
    );
  }
}