import { cookies } from 'next/headers';
import { getCookie } from 'cookies-next';
import "../components/styles/form-root.css"
import "../components/styles/form-home.css"
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "../components/layout/header"
import Footer from "../components/layout/footer"

export const metadata = {
  title: '도서관 홈페이지',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  var state = getCookie("state", {cookies});

  if(state == null){
    state = '2';
  }
  
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossOrigin="anonymous" />
      </head>
      <body>
        <Header/>
        {children}
        <Footer/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
