import "../components/styles/form-root.css"
import "../components/styles/form-home.css"
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "../components/layout/header"
import Navigation from "../components/layout/navigation"
import Footer from "../components/layout/footer"

export const metadata = {
  title: '도서관 홈페이지',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Navigation/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
